backend:
  name: github
  repo: nathankirk91/netlify-cms-gatsby-test
  branch: master

media_folder: content/assets
public_folder: assets

collections:
- name: 'blog'
  label: 'Blog'
  folder: 'content/blog'
  create: true
  slug: 'test'

  fields:
  - { label: 'Title', name: 'title', widget: 'string' }
  - { label: 'Featured Image', name: 'featuredImage', widget: 'image' }
  - { label: 'Body', name: 'body', widget: 'markdown' }